//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StylesSheetManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StylesSheetManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsControls.StylesSheetManager", typeof(StylesSheetManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been encountered when set &apos;{2}&apos; to the &apos;{1}&apos; property of the &apos;{0}&apos; control. 
        ///Only the indexed properties which implement the IList interface are supported. Moreover, the indexed properties must be defined like the following : control_name[index].property = value..
        /// </summary>
        internal static string IndexedPropertyNotCorrectlyDefinedException {
            get {
                return ResourceManager.GetString("IndexedPropertyNotCorrectlyDefinedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been encountered when reading one of the properties of the &apos;{0}&apos; style. The &apos;Name&apos; tag seems not to be present or not named correctly for this property..
        /// </summary>
        internal static string PropertyNameTagNotFoundException {
            get {
                return ResourceManager.GetString("PropertyNameTagNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been encountered  because  an invalid property (&apos;{1}&apos;) has been defined for the &apos;{0}&apos; control..
        /// </summary>
        internal static string PropertyNotFoundException {
            get {
                return ResourceManager.GetString("PropertyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been encountered  when reading the value of the &apos;{1}&apos; property of the &apos;{0}&apos; style. The &apos;Value&apos; tag seems not to be present or not named correctly for this property..
        /// </summary>
        internal static string PropertyValueTagNotFoundException {
            get {
                return ResourceManager.GetString("PropertyValueTagNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; style applied to the &apos;{1}&apos; control hasn&apos;t been found in the styles sheet file..
        /// </summary>
        internal static string StyleNotPresentInStylesSheetFileException {
            get {
                return ResourceManager.GetString("StyleNotPresentInStylesSheetFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;StylesSheetFilename&apos; key hasn&apos;t been found in the app.config file. Please, create this key (in the appSettings section) and set it to the (absolute) path of the styles sheet file to use..
        /// </summary>
        internal static string StylesSheetFileNameNotDefinedInAppConfigException {
            get {
                return ResourceManager.GetString("StylesSheetFileNameNotDefinedInAppConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The styles sheet file (defined in the app.config) hasn&apos; been found. Please, checks its path : &apos;{0}&apos;.
        /// </summary>
        internal static string StylesSheetFileNotFoundException {
            get {
                return ResourceManager.GetString("StylesSheetFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error has been encountered : 
        ///{1}.
        /// </summary>
        internal static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
    }
}
