//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace MFDService.ar.com.travelpay.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CaeCounterSoap", Namespace="http://tempuri.org/")]
    public partial class CaeCounter : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetCAEByCUITOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CaeCounter() {
            this.Url = global::MFDService.Properties.Settings.Default.MFDService_ar_com_travelpay_www_CaeCounter;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                //return base.Url;
				return ReadUrlWSConfig.UrlWSConfig("MFDService_ar_com_travelpay_www_CaeCounter");

            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetCAEByCUITCompletedEventHandler SetCAEByCUITCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetCAEByCUIT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCAEByCUIT(string cuit, string cae, string nroComprobante, double idCAEws, bool produccion) {
            this.Invoke("SetCAEByCUIT", new object[] {
                        cuit,
                        cae,
                        nroComprobante,
                        idCAEws,
                        produccion});
        }
        
        /// <remarks/>
        public void SetCAEByCUITAsync(string cuit, string cae, string nroComprobante, double idCAEws, bool produccion) {
            this.SetCAEByCUITAsync(cuit, cae, nroComprobante, idCAEws, produccion, null);
        }
        
        /// <remarks/>
        public void SetCAEByCUITAsync(string cuit, string cae, string nroComprobante, double idCAEws, bool produccion, object userState) {
            if ((this.SetCAEByCUITOperationCompleted == null)) {
                this.SetCAEByCUITOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCAEByCUITOperationCompleted);
            }
            this.InvokeAsync("SetCAEByCUIT", new object[] {
                        cuit,
                        cae,
                        nroComprobante,
                        idCAEws,
                        produccion}, this.SetCAEByCUITOperationCompleted, userState);
        }
        
        private void OnSetCAEByCUITOperationCompleted(object arg) {
            if ((this.SetCAEByCUITCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCAEByCUITCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SetCAEByCUITCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591